configurations:
    -
        host: imap.gmail.com
        port: 993
        tls: true
        tlsOptions:
            rejectUnauthorized: true
        username: phogg@tripleaughtdesign.com
        password: ''
        passwordCMD: 'keyring get mail-tad imap'
        boxes:
            -
                mailbox: INBOX
                onNewMail: 'mbsync tad'
                onNewMailPost: SKIP
