directory: ~/library/audio/music
library: ~/library/audio/.beet.blb
import:
    move: yes
ui:
    color: yes
plugins: lyrics lastgenre mbsync fetchart scrub bpd chroma convert badfiles missing
lastgenre:
    canonical: yes
    count: 3
    prefer_specific: yes
chroma:
    auto: yes
convert:
    dest: ~/sync/pixel/audio/music
    format: mp3
    copy_album_art: yes
    embed: yes
