status_path "~/.local/share/pimsync/status/"

pair contacts {
	storage_a contacts_local
	storage_b contacts_remote
	collections from b
}

storage contacts_local {
	type vdir/vcard
	path ~/library/contacts/
	fileext vcf
}

storage contacts_remote {
	type carddav
	url https://carddav.fastmail.com
	username peterhogg@fastmail.fm
	password {
		cmd keyring get mail-havenaut carddav
	}
	tls_fingerprint 313F6394E12D6187E7205329987B0AE819E62F172774607F2134F3A94B4E5250
}

pair calendar {
	storage_a calendar_local
	storage_b calendar_remote
	collections from b
}

storage calendar_local {
	type vdir/icalendar
	path ~/library/calendars/
	fileext ics
}

storage calendar_remote {
	type caldav
	url https://caldav.fastmail.com
	username peterhogg@fastmail.fm
	password {
		cmd keyring get mail-havenaut caldav
	}
	tls_fingerprint 313F6394E12D6187E7205329987B0AE819E62F172774607F2134F3A94B4E5250
}
