status_path "~/.local/share/pimsync/status/"

pair contacts {
	storage_a contacts_local
	storage_b contacts_remote
	collections from b
}

storage contacts_local {
	type vdir/vcard
	path ~/library/contacts/
	fileext vcf
}

storage contacts_remote {
	type carddav
	url https://carddav.fastmail.com
	username peterhogg@fastmail.fm
	password {
		cmd keyring get mail-havenaut carddav
	}
	tls_fingerprint F5F9CFA172B333BB10A5D1C9C51B3F870DB1F1FC58C54B902C6B5A161B0FBF4D
}

pair calendar {
	storage_a calendar_local
	storage_b calendar_remote
	collections from b
}

storage calendar_local {
	type vdir/icalendar
	path ~/library/calendars/
	fileext ics
}

storage calendar_remote {
	type caldav
	url https://caldav.fastmail.com
	username peterhogg@fastmail.fm
	password {
		cmd keyring get mail-havenaut caldav
	}
	tls_fingerprint F5F9CFA172B333BB10A5D1C9C51B3F870DB1F1FC58C54B902C6B5A161B0FBF4D
}
