status_path "~/.local/share/pimsync/status/"

pair contacts {
	storage_a contacts_local
	storage_b contacts_remote
	collections from b
}

storage contacts_local {
	type vdir/vcard
	path ~/library/contacts/
	fileext vcf
}

storage contacts_remote {
	type carddav
	url https://carddav.fastmail.com
	username peterhogg@fastmail.fm
	password {
		cmd keyring get mail-havenaut carddav
	}
	tls_fingerprint B0791568D4AAD90A7E378B9A6E48409B914E4E95D730A0724DD33F9C9FD4165A
}

pair calendar {
	storage_a calendar_local
	storage_b calendar_remote
	collections from b
}

storage calendar_local {
	type vdir/icalendar
	path ~/library/calendars/
	fileext ics
}

storage calendar_remote {
	type caldav
	url https://caldav.fastmail.com
	username peterhogg@fastmail.fm
	password {
		cmd keyring get mail-havenaut caldav
	}
	tls_fingerprint B0791568D4AAD90A7E378B9A6E48409B914E4E95D730A0724DD33F9C9FD4165A
}
